### ISSUE TITLE
Min version check

### ISSUE THREAD

**Issue by pcav** [MSBilgin/Geometry-Updater#1]
Hi.
I see you set min version at 2.12. Given that 2.8 is still our LTR, it would be good to be able to use it also there. Is >=2.12 an absolute requirement?
Thanks

**Comment by MSBilgin** [comment]
Hi,I didnt test my plugin with 2.8, but I will. 
Mehmet Selim BILGINGeological Engineer, GIS ExpertBaskent Dogalgaz Dagitim A.S.e-mail:   mselimbilgin@yahoo.com
web: cbsuygulama.wordpress.com

```
On Friday, March 18, 2016 8:53 AM, Paolo Cavallini <notifications@github.com> wrote:
```

 Hi.
I see you set min version at 2.12. Given that 2.8 is still our LTR, it would be good to be able to use it also there. Is >=2.12 an absolute requirement?
Thanks—
